### ISSUE TITLE
Could not find package click4web/declaracao-conteudo-correios at any version for your minimum-stability (stable).

### ISSUE THREAD

**Issue by and-dutra** [click4web/declaracao-conteudo-correios#1]
Boa tarde galera, estou tentando instalar  a biblioteca usando o composer, mas estou recebendo erro:
```
Could not find package click4web/declaracao-conteudo-correios at any versio  
  n for your minimum-stability (stable). Check the package spelling or your m  
  inimum-stability   
```

Tentei rodar o comando usando a flag --dev
composer require click4web/declaracao-conteudo-correios

mas não o erro persistiu, alguma ideia?

Abraço

**Comment by fontebasso** [comment]
Olá @and-dutra, vou lançar um release stable quando completar a biblioteca com outro layout de declaração (esse é o plano), mas por enquanto já está funcional e para instalar utilize o seguinte:

`composer require click4web/declaracao-conteudo-correios:v1.0.0-BETA2`

Vou atualizar a documentação, obrigado por pontuar!
